[project]
name = 'Blockchain-Based-Prescription-Eyewear-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.insurance-claim]
path = 'contracts/insurance-claim.clar'
clarity_version = 2
epoch = 2.5

[contracts.prescription-issuance]
path = 'contracts/prescription-issuance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
